import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import { SongProvider } from "./context/song-context";
import { FavoritesProvider } from "./context/favorites-context";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Youth Group Songs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased [--header-height:calc(--spacing(14))]`}>
        <MainProvider>
          <SidebarProvider className="flex flex-col">
            <Navbar />
            <div className="flex flex-1">
              <AppSidebar />
              <SidebarInset>{children}</SidebarInset>
            </div>
          </SidebarProvider>
        </MainProvider>
      </body>
    </html>
  );
}

function MainProvider({ children }: { children: ReactNode }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <SongProvider>
        <FavoritesProvider>{children}</FavoritesProvider>
      </SongProvider>
    </ThemeProvider>
  );
}
